ex11/StarWarsHeroes/Models/ErrorViewModel.cs
using System;

namespace StarWarsHeroes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ex11/StarWarsHeroes/Models/Film.cs
using System.Text.Json.Serialization;

namespace StarWarsHeroes.Models
{
    public class Film
    {
        [JsonPropertyName("title")]
        public string Title { get; set; }
        
        [JsonPropertyName("release_date")]
        public string ReleaseDate { get; set; }
    }
}

ex11/StarWarsHeroes/Models/Hero.cs
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace StarWarsHeroes.Models
{
    public class Hero
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }
        
        [JsonPropertyName("hair_color")]
        public string HairColor { get; set; }
        
        [JsonPropertyName("skin_color")]
        public string SkinColor { get; set; }
        
        [JsonPropertyName("gender")]
        public string Gender { get; set; }
        
        // [JsonPropertyName("films")]
        // public List<Film> Films { get; set; }
    }
}

ex11/StarWarsHeroes/Models/Heroes.cs
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace StarWarsHeroes.Models
{
    public class Heroes
    {
        [JsonPropertyName("results")]
        public List<Hero> HeroesList { get; set; }

        public int NumberOfHeroes => HeroesList.Count;
    }
}

ex11/StarWarsHeroes/Controllers/HeroController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StarWarsHeroes.Models;
using StarWarsHeroes.Services;

namespace StarWarsHeroes.Controllers
{
    public class HeroController : Controller
    {
        private IHeroService _service;

        public HeroController(IHeroService service) => _service = service;

        
        
    }
}

ex11/StarWarsHeroes/Controllers/HeroesController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using StarWarsHeroes.Models;
using StarWarsHeroes.Services;

namespace StarWarsHeroes.Controllers
{
    public class HeroesController : Controller
    {
        private static IHeroService _service = new HeroService();
        
        
        
        public async Task<IActionResult> Heroes()
        {
            return View(await _service.GetHeroes());
        }
    }
}

ex11/StarWarsHeroes/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using StarWarsHeroes.Models;

namespace StarWarsHeroes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ex11/StarWarsHeroes/Views/Heroes/Heroes.cshtml
@model StarWarsHeroes.Models.Heroes

@{
    ViewBag.Title = "Star Wars Heroes";
    Layout = "_Layout";
}

<h2>Star Wars Heroes</h2>
@foreach (var hero in Model.HeroesList)
{
    <p>@hero.Name : Gender: @hero.Gender ; Hair Color: @hero.HairColor;  Skin Color: @hero.SkinColor</p>
}

ex11/StarWarsHeroes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

ex11/StarWarsHeroes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - StarWarsHeroes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StarWarsHeroes</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Heroes" asp-action="Heroes">Heroes</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2022 - StarWarsHeroes - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>